#!/usr/bin/env bash

# Package Inventory Module
# Collects explicitely installed packages (pacman + AUR)
# Separates official packages from AUR packages
# Generates declarative package lists for reproducible installations

set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
readonly INVENTORY_DIR="${SCRIPT_DIR}"
readonly TIMESTAMP=$(date +%Y%m%d_%H%M%S)

# Colors for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*"
}

# Get explicitly installed packages from pacman
get_pacman_packages() {
    local output_file="${1}"
    
    log_info "Collecting explicitly installed pacman packages..."
    
    # Get explicitly installed packages (not as dependencies)
    # This is crucial for declarative management - only packages the user explicitly installed
    pacman -Qqe | grep -v '^$' | sort > "${output_file}"
    
    local package_count=$(wc -l < "${output_file}")
    log_success "Found ${package_count} explicitly installed packages"
}

# Separate AUR packages from official packages
separate_aur_packages() {
    local all_packages="${1}"
    local aur_packages="${2}"
    local official_packages="${3}"
    
    log_info "Separating AUR packages from official packages..."
    
    # Get list of official repositories
    local official_repos=(core extra community multilib)
    
    # Check each package against official repositories
    while IFS= read -r package; do
        [[ -z "${package}" ]] && continue
        
        # Check if package exists in any official repository
        local is_official=false
        for repo in "${official_repos[@]}"; do
            if pacman -Sl "${repo}" | grep -q "^${repo} ${package} "; then
                is_official=true
                break
            fi
        done
        
        if [[ "${is_official}" == "true" ]]; then
            echo "${package}" >> "${official_packages}"
        else
            # Likely an AUR package or from custom repository
            echo "${package}" >> "${aur_packages}"
        fi
    done < "${all_packages}"
    
    local official_count=$(wc -l < "${official_packages}" 2>/dev/null || echo 0)
    local aur_count=$(wc -l < "${aur_packages}" 2>/dev/null || echo 0)
    
    log_success "Separated: ${official_count} official packages, ${aur_count} AUR packages"
}

# Generate declarative package configuration
generate_declarative_config() {
    local official_packages="${1}"
    local aur_packages="${2}"
    local declarative_file="${3}"
    
    log_info "Generating declarative package configuration..."
    
    cat > "${declarative_file}" << EOF
# Declarative Package Configuration
# Generated on: $(date)
# This file defines what packages SHOULD be installed
# Edit this file to declare desired state, not current state

# Official packages (from Arch repositories)
# These will be installed using pacman
$(while IFS= read -r package; do
    [[ -n "${package}" ]] && echo "package.official.${package}=required"
done < "${official_packages}")

# AUR packages (from Arch User Repository)
# These require an AUR helper (yay, paru, etc.)
$(while IFS= read -r package; do
    [[ -n "${package}" ]] && echo "package.aur.${package}=required"
done < "${aur_packages}")

# Package groups or patterns
# Example: package.group.base-devel=required
# Example: package.pattern.linux-lts=required

# Package exclusions (never install these)
# Example: package.exclude.unwanted-package=true

EOF
    
    log_success "Declarative configuration generated: ${declarative_file}"
}

# Generate installation script for packages
generate_install_script() {
    local official_packages="${1}"
    local aur_packages="${2}"
    local install_script="${3}"
    
    log_info "Generating package installation script..."
    
    cat > "${install_script}" << 'EOF'
#!/usr/bin/env bash
# Package Installation Script
# Auto-generated by infra-backup

set -euo pipefail

readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*"
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root"
        exit 1
    fi
}

# Detect AUR helper
detect_aur_helper() {
    local aur_helpers=(yay paru aura)
    
    for helper in "${aur_helpers[@]}"; do
        if command -v "${helper}" >/dev/null 2>&1; then
            echo "${helper}"
            return 0
        fi
    done
    
    return 1
}

# Install official packages
install_official_packages() {
    local package_list=(
EOF

    # Add official packages to the script
    while IFS= read -r package; do
        [[ -n "${package}" ]] && echo "        ${package}" >> "${install_script}"
    done < "${official_packages}"
    
    cat >> "${install_script}" << 'EOF'
    )
    
    log_info "Installing official packages..."
    
    if [[ ${#package_list[@]} -gt 0 ]]; then
        pacman -Syu --needed --noconfirm "${package_list[@]}"
        log_success "Official packages installed successfully"
    else
        log_info "No official packages to install"
    fi
}

# Install AUR packages
install_aur_packages() {
    local package_list=(
EOF

    # Add AUR packages to the script
    while IFS= read -r package; do
        [[ -n "${package}" ]] && echo "        ${package}" >> "${install_script}"
    done < "${aur_packages}"
    
    cat >> "${install_script}" << 'EOF'
    )
    
    if [[ ${#package_list[@]} -gt 0 ]]; then
        local aur_helper
        aur_helper=$(detect_aur_helper)
        
        if [[ -z "${aur_helper}" ]]; then
            log_error "No AUR helper found. Please install yay, paru, or aura"
            log_info "Recommended: pacman -S yay"
            return 1
        fi
        
        log_info "Installing AUR packages using ${aur_helper}..."
        
        # Install packages
        if [[ "${aur_helper}" == "yay" ]] || [[ "${aur_helper}" == "paru" ]]; then
            "${aur_helper}" -S --needed --noconfirm "${package_list[@]}"
        else
            # For other AUR helpers, try generic approach
            "${aur_helper}" -S "${package_list[@]}"
        fi
        
        log_success "AUR packages installed successfully"
    else
        log_info "No AUR packages to install"
    fi
}

# Main installation function
main() {
    check_root
    
    log_info "Starting package installation..."
    
    # Update package databases
    log_info "Updating package databases..."
    pacman -Sy
    
    install_official_packages
    install_aur_packages
    
    log_success "Package installation completed!"
}

# Run main if not sourced
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi

EOF
    
    chmod +x "${install_script}"
    log_success "Installation script generated: ${install_script}"
}

# Main inventory function
main() {
    local temp_all="${INVENTORY_DIR}/all_packages_${TIMESTAMP}.tmp"
    local temp_aur="${INVENTORY_DIR}/aur_packages_${TIMESTAMP}.tmp"
    local temp_official="${INVENTORY_DIR}/official_packages_${TIMESTAMP}.tmp"
    
    local inventory_file="${INVENTORY_DIR}/packages_${TIMESTAMP}.inventory"
    local declarative_file="${PROJECT_ROOT}/declarative/system.conf"
    local install_script="${INVENTORY_DIR}/install_packages.sh"
    
    # Step 1: Collect all packages
    get_pacman_packages "${temp_all}"
    
    # Step 2: Separate AUR from official
    separate_aur_packages "${temp_all}" "${temp_aur}" "${temp_official}"
    
    # Step 3: Create inventory summary
    cat > "${inventory_file}" << EOF
# Package Inventory
# Generated on: $(date)
# Host: $(hostname)

## Total Explicitly Installed Packages: $(wc -l < "${temp_all}")

### Official Packages ($(wc -l < "${temp_official}"))
$(cat "${temp_official}")

### AUR Packages ($(wc -l < "${temp_aur}"))
$(cat "${temp_aur}")

### Raw Package List
$(cat "${temp_all}")

EOF
    
    log_success "Inventory saved: ${inventory_file}"
    
    # Step 4: Generate declarative configuration
    generate_declarative_config "${temp_official}" "${temp_aur}" "${declarative_file}"
    
    # Step 5: Generate installation script
    generate_install_script "${temp_official}" "${temp_aur}" "${install_script}"
    
    # Cleanup temporary files
    rm -f "${temp_all}" "${temp_aur}" "${temp_official}"
    
    log_info "Package inventory completed successfully"
    log_info "Next steps:"
    log_info "  1. Review ${declarative_file}"
    log_info "  2. Edit to declare desired state (remove unwanted packages)"
    log_info "  3. Use ${install_script} to reproduce installation"
}

# Run main if not sourced
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi